### ISSUE TITLE
Training and Testing pro

### ISSUE THREAD

**Issue by mausLe** [taufeeque9/HumanFallDetection#4]
Hi, 

I have some questions about this repo:
- Which subjects of the HAR-UP dataset had been used to train and validate this model.
- Do you have any document of choosing parameters while training the LSTM model. If does, could you share these?

Thanks for sharing this wonderful repo!

**Comment by taufeeque9** [comment]
The information about the dataset and the model is available in the paper of this project.

**Comment by mausLe** [comment]
Thanks for replying to this.
