### ISSUE TITLE
TypeError: cli() got an unexpected keyword argument 'force_complete_pose'

### ISSUE THREAD

**Issue by makeenmajlis** [taufeeque9/HumanFallDetection#6]
After installing all the requirements, I get this error when trying to run the Python file:

![image](https://user-images.githubusercontent.com/52301034/111912713-403a4500-8a41-11eb-9de5-feb9ccb019f4.png)

**Comment by RyanCV** [comment]
same error here. If change the position of the variables, using `openpifpaf.decoder.cli(parser, instance_threshold=0.2, seed_threshold=0.5, force_complete_pose=True)`, it still got the error: 
`Traceback (most recent call last):
  File "fall_detector.py", line 151, in <module>
    f = FallDetector()
  File "fall_detector.py", line 31, in __init__
    self.args = self.cli()
  File "fall_detector.py", line 39, in cli
    openpifpaf.decoder.cli(parser, instance_threshold=0.2, seed_threshold=0.5, force_complete_pose=True)
TypeError: cli() got an unexpected keyword argument 'instance_threshold'`. 

Any idea how to solve it?

**Comment by TVI-BIZ** [comment]
Same issue here:
pip uninstall openpifpaf
pip install openpifpaf==0.11.7
and you are good to go.
Can confirm that is work with cuda 11 and RTX 30*. tested in RTX 3060 - 12GB.
by default it use CUDA less then 11, but only CUDA 11 support RTX30*
So if you want to use CUDA 11.
pip uninstall torch
pip uninstall torchvision
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by cqn2020** [comment]
same error

**Comment by luyao2001** [comment]
when run 'python fall_detector.py', a error accured: TypeError: cli() got an unexpected keyword argument 'force_complete_pose'
