### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by luyao2001** [taufeeque9/HumanFallDetection#8]
Hey, thanks for sharing a good repository. Can please share the LSTM 2sec_multi_train_data.csv? Thanks!

**Comment by taufeeque9** [comment]
I don't have that file, unfortunately. That file was obtained by extracting the input features for our model from the videos in the [HAR-UP dataset](https://sites.google.com/up.edu.mx/har-up/). You can download this dataset and extract relevant features from it.
