### ISSUE TITLE
the train

### ISSUE THREAD

**Issue by luyao2001** [taufeeque9/HumanFallDetection#9]
Hello, can you give me the training python script and the training dataset files? I am glad to if you could? Thank you very much!

**Comment by rxc23** [comment]
Hello, what is the operating environment of this experiment? Can you list it specifically

**Comment by javasmall** [comment]
Hello, can you give me the training python script and the training dataset files? I am glad to if you could? Thank you very much!
My email is 1315426911@qq.com

**Comment by anhldq-0164** [comment]
Hi, can you provide me the trainning scripts and dataset files? i'm learning about human fall.
Thank you so much! 
My email is aluong343@gmail.com

**Comment by lbbbbbbbbbb** [comment]
Hi, can you provide me the trainning scripts and dataset files? i'm learning about human fall.
Thank you so much!
My email is 1607304404@qq.com

**Comment by thehalocline** [comment]
Hello! I am researching on Human Fall Detection Projects and I really need datasets and training scripts.
If you don't mind could you send me them please? My email is psuny0412@gmail.com

**Comment by murasakirua** [comment]
Hello, can you give me the training python script and the training dataset files? I work on fall detection research. Thank you very much. My email is mengxiang202010@yahoo.co.jp

**Comment by letranquanghuy** [comment]
Hello, I am researching on Human Fall Detection Projects. Can you provide me the training python script and the training dataset files? Thank you for all your support. My email is letranquanghuy0204@gmail.com

**Comment by taufeeque9** [comment]
Unfortunately, I don't have the processed dataset files and the training script. The processed dataset files containing the features that our model uses was obtained by extracting them from the videos in the [HAR-UP dataset](https://sites.google.com/up.edu.mx/har-up/). You can download this dataset and extract the relevant features from it.
You can train the model using PyTorch with the model class available in model/model.py. All the parameters related to training can be found in our [paper](https://doi.org/10.1117/12.2580700).
